import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Masthead from '../components/masthead'
import AboutMe from '../components/aboutme'
import Contact from '../components/contact'
import Timeline from '../components/timeline'
import Project from '../components/projects'
import { ApolloClient, InMemoryCache, createHttpLink, gql } from '@apollo/client';
import { setContext } from '@apollo/client/link/context';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anant Ojha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <AboutMe />
      <Timeline />
      <Project />
      <Contact />
      
    </div>
  )
}

export default Home
